import { test, expect } from "@playwright/test";
import sharp from "sharp";
import { Pool } from "pg";
import { randomUUID } from "node:crypto";
import { execFile } from "node:child_process";
import { promisify } from "node:util";
import { resolve } from "node:path";
import { createAccount, cleanupAccounts } from "../helpers/auth-fixture";
const exec = promisify(execFile);
test.afterAll(async () => cleanupAccounts());
test("real matching worker: criteria restore, sorting, failure retention, privacy and ko/en mobile", async ({ page, baseURL, browser }) => {
  test.setTimeout(240000);
  page.setDefaultTimeout(15000);
  if (!process.env.TEST_DATABASE_URL || new URL(process.env.TEST_DATABASE_URL).pathname !== "/claps_test") throw new Error("ISOLATED_DB_REQUIRED");
  const pool = new Pool({ connectionString: process.env.TEST_DATABASE_URL }), ids = [randomUUID(), randomUUID()];
  const headers = { Origin: baseURL! };
  const run = () => process.env.E2E_EXTERNAL_WORKER === "1" ? Promise.resolve() : exec(process.execPath, ["--conditions=react-server", "--import", "tsx", resolve("tests/helpers/phase9-worker.ts")], { env: { ...process.env, DATABASE_URL: process.env.TEST_DATABASE_URL, APP_ORIGIN: baseURL }, timeout: 90000 });
  await createAccount(page.request, baseURL!);
  await page.request.post("/api/locale", { headers, data: { locale: "en" } });
  try {
    for (const [i, words] of [[0, "cute"], [1, "sport"]] as const) await pool.query("INSERT INTO partners(id,name,contact_email,visibility,profile) VALUES($1,$2,'fixture@example.test','public',$3)", [ids[i], i === 0 ? "P9 Paper" : "P9 Sports", { schemaVersion: 1, description: words, tags: [words], ipNames: [], marketDescription: i === 0 ? "stationery" : "apparel", images: [] }]);
    await page.goto("/partners/criteria");
    await page.getByLabel("Upload image", { exact: true }).setInputFiles({ name: "reference.png", mimeType: "image/png", buffer: await sharp({ create: { width: 12, height: 12, channels: 3, background: "red" } }).png().toBuffer() });
    await expect(page.getByRole("img", { name: "reference.png" })).toBeVisible();
    await page.getByLabel("World attributes", { exact: true }).fill("cute");
    await page.getByLabel("Licensee attributes (your company)", { exact: true }).fill("cute");
    await page.locator('#industries').fill('apparel');
    await page.getByRole("button", { name: "Save and view matches", exact: true }).click();
    await expect(page).toHaveURL(/\/partners$/); await run();
    await expect(page.getByTestId("match-hero")).toContainText("P9 Paper", { timeout: 15000 });
    await page.getByRole("combobox").selectOption("industry");
    await expect(page.getByTestId("match-hero")).toContainText("P9 Sports");
    await expect(page.getByTestId("match-list")).toContainText("P9 Paper");
    const latest = (await (await page.request.get("/api/matches/latest")).json()).data;
    const original = latest.result.jobId;
    await page.goto("/partners/criteria"); await expect(page.getByLabel("World attributes", { exact: true })).toHaveValue("cute");
    await expect(page.getByRole("img", { name: "reference.png" })).toBeVisible();
    await page.getByLabel("World attributes", { exact: true }).fill("sport");
    await page.getByLabel("Licensee attributes (your company)", { exact: true }).fill("sport");
    await page.getByRole("button", { name: "Save and view matches", exact: true }).click();
    await expect(page).toHaveURL(/\/partners$/);
    const second = (await (await page.request.get("/api/matches/latest")).json()).data.attempt;
    // Inject a failed attempt only in the isolated DB to exercise the production failure UI.
    await pool.query("UPDATE jobs SET status='failed',error_code='INVALID_RESULT',finished_at=now() WHERE id=$1 AND status='queued'", [second.id]);
    await expect(page.getByText("The latest recommendation failed or was canceled. Previous successful results are retained.")).toBeVisible();
    expect((await (await page.request.get("/api/matches/latest")).json()).data.result.jobId).toBe(original);
    await page.getByRole("button", { name: "Match again", exact: true }).click(); await run();
    await expect(page.getByTestId("match-hero")).toContainText("P9 Sports");
    await page.getByTestId("match-hero").getByRole("button", { name: "IP details", exact: true }).click();
    await expect(page.getByRole("dialog")).toContainText("fixture@example.test");
    await page.context().grantPermissions([]);
    await page.getByRole("button", { name: "Copy", exact: true }).click();
    await expect(page.getByRole("dialog").getByRole("alert")).toContainText("Your browser did not allow copying");
    await page.context().grantPermissions(["clipboard-read", "clipboard-write"]);
    await page.getByRole("button", { name: "Copy", exact: true }).click();
    await expect(page.getByRole("button", { name: "Copied", exact: true })).toBeVisible();
    expect(await page.evaluate(() => navigator.clipboard.readText())).toBe("fixture@example.test");
    await page.keyboard.press("Escape");
    const other = await browser.newContext(); await createAccount(other.request, baseURL!);
    expect((await (await other.request.get("/api/matches/latest")).json()).data.result).toBeNull();
    expect((await other.request.get(`/api/jobs/${original}`)).status()).toBe(404); await other.close();
    expect((await page.request.put("/api/me/matching-criteria", { headers: { Origin: "https://foreign.test" }, data: {} })).status()).toBe(403);
    const beforeLanguage = (await (await page.request.get("/api/matches/latest")).json()).data.attempt.id;
    await page.request.post("/api/locale", { headers, data: { locale: "ko" } }); await page.reload();
    await expect(page.getByRole("main").getByRole("heading", { name: "파트너 추천", exact: true })).toBeVisible();
    expect((await (await page.request.get("/api/matches/latest")).json()).data.attempt.id).toBe(beforeLanguage);
    await page.setViewportSize({ width: 390, height: 844 }); expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
    await page.screenshot({ path: "md/evidence/phase9/matching-mobile.png", fullPage: true });
    await pool.query("UPDATE partners SET visibility='private' WHERE id=$1", [ids[1]]);
    await expect(page.getByTestId("match-hero")).toHaveCount(0, { timeout: 15000 });
    expect((await page.request.get(`/api/partners/${ids[1]}`)).status()).toBe(404);
    expect((await (await page.request.get("/api/matches/latest")).json()).data.result.items).toEqual([]);
  } finally { await pool.query("DELETE FROM partners WHERE id=ANY($1)", [ids]); await pool.end(); }
});
