// Fictional fixtures, not endorsements, real contacts, or AI results.
export const demoPartners = [
  { key: "stationery", ko: "샘플 · 달빛 문구", en: "Sample · Moonlit Stationery", koDescription: "가상 샘플 파트너입니다. 귀여움과 일상을 주제로 노트·스티커·종이 제품을 기획합니다.", enDescription: "Fictional sample partner planning notebooks, stickers and paper goods inspired by cute everyday moments.", tags: ["문구", "stationery", "귀여움", "cute", "일상", "everyday"], marketKo: "문구·종이 제품 분야의 샘플 소개입니다. 실적이나 계약 가능성을 나타내지 않습니다.", marketEn: "Sample stationery and paper goods profile. It does not represent actual sales or availability." },
  { key: "apparel", ko: "샘플 · 파도 의류", en: "Sample · Wave Apparel", koDescription: "가상 샘플 파트너입니다. 스포츠와 활동적인 일상을 주제로 티셔츠·모자를 기획합니다.", enDescription: "Fictional sample partner planning T-shirts and caps around sports and active everyday life.", tags: ["의류", "apparel", "스포츠", "sport", "일상", "everyday"], marketKo: "의류 분야의 샘플 소개입니다. 실제 생산·판매 정보가 아닙니다.", marketEn: "Sample apparel profile, not actual production or sales information." },
  { key: "home", ko: "샘플 · 숲속 리빙", en: "Sample · Forest Living", koDescription: "가상 샘플 파트너입니다. 자연과 휴식을 주제로 컵·쿠션·생활 소품을 기획합니다.", enDescription: "Fictional sample partner planning cups, cushions and home accessories inspired by nature and relaxation.", tags: ["리빙", "home", "자연", "nature", "휴식", "relaxation"], marketKo: "생활 소품 분야의 샘플 소개입니다. 실제 인증이나 환경 성과를 주장하지 않습니다.", marketEn: "Sample home accessories profile. No actual certification or environmental performance is claimed." },
  { key: "toys", ko: "샘플 · 별빛 완구", en: "Sample · Starlight Toys", koDescription: "가상 샘플 파트너입니다. 우정과 모험을 주제로 캐릭터 인형·퍼즐을 기획합니다.", enDescription: "Fictional sample partner planning character plush toys and puzzles around friendship and adventure.", tags: ["완구", "toys", "우정", "friendship", "모험", "adventure", "귀여움", "cute"], marketKo: "완구 분야의 샘플 소개입니다. 실제 제품이나 안전 인증 정보가 아닙니다.", marketEn: "Sample toy profile, not actual product or safety certification information." },
  { key: "packaging", ko: "샘플 · 작은상자 패키지", en: "Sample · Little Box Packaging", koDescription: "가상 샘플 파트너입니다. 선물과 계절 행사를 주제로 종이 상자·포장지를 기획합니다.", enDescription: "Fictional sample partner planning paper boxes and wrapping paper for gifts and seasonal events.", tags: ["패키지", "packaging", "선물", "gift", "종이", "paper"], marketKo: "패키지 분야의 샘플 소개입니다. 실제 견적이나 납기를 제공하지 않습니다.", marketEn: "Sample packaging profile. No actual quotation or delivery schedule is offered." },
  { key: "digital", ko: "샘플 · 구름 디지털", en: "Sample · Cloud Digital", koDescription: "가상 샘플 파트너입니다. 캐릭터와 일상을 주제로 디지털 스티커·배경화면을 기획합니다.", enDescription: "Fictional sample partner planning digital stickers and wallpapers around characters and everyday life.", tags: ["디지털", "digital", "캐릭터", "character", "일상", "everyday"], marketKo: "디지털 콘텐츠 분야의 샘플 소개입니다. 실제 서비스 제휴를 의미하지 않습니다.", marketEn: "Sample digital content profile. It does not imply an actual service partnership." },
] as const;
export const demoProjects = [
  { name: "샘플 · 구름친구 문구", ip: "샘플 IP · 구름친구 / Cloud Pals", session: "샘플 · 노트와 스티커 기획", description: "가상 문구 프로젝트입니다. Sample stationery project. 실제 생성·검증 결과는 포함하지 않습니다. No AI results included." },
  { name: "샘플 · 파도친구 의류", ip: "샘플 IP · 파도친구 / Wave Pals", session: "샘플 · 티셔츠 기획", description: "가상 의류 프로젝트입니다. Sample apparel project. 실제 생성·검증 결과는 포함하지 않습니다. No AI results included." },
  { name: "샘플 · 숲속친구 리빙", ip: "샘플 IP · 숲속친구 / Forest Pals", session: "샘플 · 컵과 쿠션 기획", description: "가상 리빙 프로젝트입니다. Sample homeware project. 실제 생성·검증 결과는 포함하지 않습니다. No AI results included." },
] as const;
export const demoCriteria = { revision: 1, ipName: "", category: "", licensee: "", revenue: "", industries: ["문구", "stationery"], styles: [], worldView: "귀여움 cute 일상 everyday", collaborationHistory: "" };
